- id: check-message
  name: check message formatting
  description: prevents unconventional commits from being committed.
  entry: commit-check
  args: ["--message"]
  pass_filenames: false
  language: python
  always_run: true
- id: check-branch
  name: check branch naming
  description: prevents unconventional branch from being pushed to remote repo.
  entry: commit-check
  args: ["--branch"]
  pass_filenames: false
  language: python
  always_run: true
