- id: check-message
  name: check commit message
  description: requiring commit message to match regex
  entry: commit-check
  args: [--message]
  pass_filenames: false
  language: python
- id: check-branch
  name: check branch naming
  description: requiring branch naming to match regex
  entry: commit-check
  args: [--branch]
  pass_filenames: false
  language: python
- id: check-author-name
  name: check committer name
  description: requiring committer name to match regex
  entry: commit-check
  args: [--author-name]
  pass_filenames: false
  language: python
- id: check-author-email
  name: check committer email
  description: requiring committer email to match regex
  entry: commit-check
  args: [--author-email]
  pass_filenames: false
  language: python
