name: Commit Check
description: Check commit message formatting, branch naming, referencing Jira tickets, and more
author: shenxianpeng
branding:
  icon: "check-circle"
  color: "green"
inputs:
  check-message:
    description: prevents unconventional commits from being committed.
    required: false
    default: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'
  check-branch:
    description: prevents unconventional branch from being pushed to remote repo.
    required: false
    default: '^(bugfix|feature|release|hotfix|task)\/[\w-.]+|(master)|(main)'
outputs:
  checks-failed:
    description: An integer that can be used as a boolean value to indicate if all checks failed.
runs:
  using: "composite"
  steps:
    - name: Install action dependencies
      shell: bash
      run: python3 -m pip install git@github.com:commit-check/commit-check.git@main
    - name: Run commit-check
      id: commit-check
      shell: bash
      run: |
        commit-check \
          --check-message="${{ inputs.check-message }}" \
          --check-branch="${{ inputs.check-branch }}"
