name: Commit Check
description: Check commit message formatting, branch naming, referencing Jira tickets, and more
author: shenxianpeng
branding:
  icon: "check-circle"
  color: "green"
inputs:
  message:
    description: prevents unconventional commits from being committed.
    required: false
    default: 'true'
  branch:
    description: prevents unconventional branch from being pushed to remote repo.
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Run commit-check
      id: commit-check
      shell: bash
      run: |
        if [ ${{ inputs.message }} == 'true' ]; then
          commit-check --message
        fi
        if [ ${{ inputs.branch }} == 'true' ]; then
          commit-check --branch
        fi
