name: PR Auto-labeler

on:
  # pull_request event is required for auto-labeler
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  draft-release:
    uses: commit-check/.github/.github/workflows/pr-labeler.yml@main
