name: publish package

on:
  release:
    branches: [main]
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # use fetch --all for setuptools_scm to work
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: '3.x'

    - name: Build wheel
      run: |
        # Install dependencies
        python -m pip install --upgrade pip twine
        # Build wheel
        python -m pip wheel -w dist .
        # Check distribution
        twine check dist/commit_check*

    - name: Create attestations
      uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
      with:
        subject-path: "dist/commit_check*"

    - name: Publish package to TestPyPI
      if: github.event_name == 'workflow_dispatch' && github.repository == 'commit-check/commit-check'
      uses: pypa/gh-action-pypi-publish@6733eb7d741f0b11ec6a39b58540dab7590f9b7d # v1.14.0
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_TOKEN }}
      continue-on-error: true

    - name: Publish package to PyPI
      if: github.event_name != 'workflow_dispatch' && github.repository == 'commit-check/commit-check'
      uses: pypa/gh-action-pypi-publish@6733eb7d741f0b11ec6a39b58540dab7590f9b7d # v1.14.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
