name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-release:
    uses: commit-check/.github/.github/workflows/release-drafter.yml@main
