name: Tag and Commit Check

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to update to'
        default: 'latest'
        required: true
      ref:
        description: 'which branch to update the tag on'
        default: 'main'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Config git name and email
      run: |
        git config user.name 'github-actions'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Update tag with parameter
      if: github.event.inputs.tag != ''
      run: |
        git tag --delete ${{ inputs.tag }}  || true
        git push --delete origin ${{ inputs.tag }} || true
        git tag -a ${{ inputs.tag }} -m 'Retag ${{ inputs.tag }}'
        git push origin ${{ inputs.tag }}
    - name: Update tag to latest
      if: github.event.inputs.tag == ''
      run: |
        git tag --delete latest || true
        git push --delete origin latest || true
        git tag -a latest -m 'Retag latest'
        git push origin latest

  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: commit-check/commit-check@latest
        id: check
        with:
          message: true
          branch: true
